### ISSUE TITLE
issue in using this widget in my app

### ISSUE THREAD

**Issue by CommitTeddy** [angular-dashboard-framework/adf-widget-table#1]
I have got my sample app running with bunch of widgets (clock, linklist, weater etc) .  I also need a table widget on my app.

When I add it to my sample.js  ---> 

```
angular.module('sample', [
  'adf', 'adf.structures.base','adf.widget.table','adf.widget.clock','adf.widget.linklist','adf.widget.weather','adf.widget.markdown','adf.widget.randommsg','ngRoute','LocalStorageModule'
])
```

I am getting this error - 
Error: [$injector:nomod] Module 'adf.widget.table' is not available!

I have table min.js & adf-widget-table.js in my index.html as per the documentation  - 

`<script type="text/javascript" src="../bower_components/showdown/compressed/extensions/table.min.js"></script>
<script type="text/javascript" src="widgets/adf-widget-table/dist/adf-widget-table.min.js"></script>`

also, I had to built the adf-widget-table locally as the bower module did not have 'dist' directory.

What could be wrong here? is something missing on adf-widget-table.min.js??

**Comment by sdorra** [comment]
I've released now v0.1.0 of this widget. You should now be able to use the widget with bower.
